// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVsi9hNbGDO0MjFhCxrzE1kZc6WPbWZU0',
    appId: '1:427055348909:web:1f83436c2899daef2a5a24',
    messagingSenderId: '427055348909',
    projectId: 'wheel-faster-store-2e75c',
    authDomain: 'wheel-faster-store-2e75c.firebaseapp.com',
    storageBucket: 'wheel-faster-store-2e75c.appspot.com',
    measurementId: 'G-BKR4ZDDMNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoS_caf4xcvhlKq8KiH6vJ7_680Nf6wJo',
    appId: '1:427055348909:android:fd42b92858dda69f2a5a24',
    messagingSenderId: '427055348909',
    projectId: 'wheel-faster-store-2e75c',
    storageBucket: 'wheel-faster-store-2e75c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyY7utWTiklcngDnLSQPR3O84Mhg_IAAU',
    appId: '1:427055348909:ios:3673b8b5e51cf1ef2a5a24',
    messagingSenderId: '427055348909',
    projectId: 'wheel-faster-store-2e75c',
    storageBucket: 'wheel-faster-store-2e75c.appspot.com',
    androidClientId: '427055348909-9uasg7t03v6r59a6gmod9aja6k5tn87b.apps.googleusercontent.com',
    iosClientId: '427055348909-hmm6rr02dh51sbj36j8res7ri8rklteq.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyY7utWTiklcngDnLSQPR3O84Mhg_IAAU',
    appId: '1:427055348909:ios:3673b8b5e51cf1ef2a5a24',
    messagingSenderId: '427055348909',
    projectId: 'wheel-faster-store-2e75c',
    storageBucket: 'wheel-faster-store-2e75c.appspot.com',
    androidClientId: '427055348909-9uasg7t03v6r59a6gmod9aja6k5tn87b.apps.googleusercontent.com',
    iosClientId: '427055348909-hmm6rr02dh51sbj36j8res7ri8rklteq.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVsi9hNbGDO0MjFhCxrzE1kZc6WPbWZU0',
    appId: '1:427055348909:web:66276d98ff06ee752a5a24',
    messagingSenderId: '427055348909',
    projectId: 'wheel-faster-store-2e75c',
    authDomain: 'wheel-faster-store-2e75c.firebaseapp.com',
    storageBucket: 'wheel-faster-store-2e75c.appspot.com',
    measurementId: 'G-LRRBNYGMWS',
  );
}
